version: "3.7"
services:
  consul:
    image: hashicorp/consul:1.11.2
    container_name: consul-server1
    restart: always
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=3"

networks:
  consul:
    driver: bridge
